### ISSUE TITLE
[Bug] Kitten + rocketship animation

### ISSUE THREAD

**Issue by elizabethyalkut** [lzacharkow/tabby-cat-support#2]
When I open a tab with the rocket ship toy and it attracts a kitten, the kitten and rocketship animation is unsynced, and it's really creepy.

![tabbycat](https://user-images.githubusercontent.com/593970/27974864-c96b2036-632d-11e7-8b6c-311c031b12eb.gif)

Chrome 59.0.3071.115

**Comment by lzacharkow** [comment]
Oh weird, that's really creepy. Does this happen every time? What OS do you have?

**Comment by elizabethyalkut** [comment]
Everytime there's a kitten + rocketship combo, yeah. OSX 10.12.5. I have a ton of other extensions, which I'm happy to list out if you think it'll be useful, and this only started happening recently, like in the last couple of weeks or so, but I didn't notice exactly when, sorry.

**Comment by lzacharkow** [comment]
It would be useful to know what other extensions you have, thank you! I've seen that issue happen in Firefox but not in Chrome. Hmmm...

**Comment by elizabethyalkut** [comment]
1Password Beta 4.6.8.1
Boomerang for Gmail 1.2.7
ColorZilla 2.0
Event Colors 0.1
Evernote Web Clipper 6.12.1
Favicon Changer 1.0.3
Ghostery 7.2.2
Google Docs 0.9
Google Docs Offline 1.4
Google Sheets 1.1
Google Slides 0.9
Hide Twitter Guff 4.3
PostureMinder 1.3.1
Privacy Badger 2017.6.13.1
Shut Up 3.0.3
Tabby Cat 0.995
Tampermonkey 4.3.6
Word Count 1.2

**Comment by lzacharkow** [comment]
Hey there! Is this still happening for you? I'm sorry I haven't followed up in a while. I believe this might have been fixed in a recent web standards update... but not sure.

**Comment by elizabethyalkut** [comment]
Yep, still happening. Anything I can test?

**Comment by elizabethyalkut** [comment]
This has magically stopped happening for me. Because computers.
