### ISSUE TITLE
Chrome Extension cannot install

### ISSUE THREAD

**Issue by Timmatt-Lee** [lzacharkow/tabby-cat-support#28]
https://chrome.google.com/webstore/detail/tabby-cat/mefhakmgclhhfbdadeojlkbllmecialg?hl=en
site is down, any update?

**Comment by TamRiceCS** [comment]
Oh my goodness I thought I was the only one, I saw a friend w/ the extension and I want it so bad!

**Comment by Timmatt-Lee** [comment]
Looks like it's alive. Close it now :)
