### ISSUE TITLE
 [bug] Address bar not automatically selected in Firefox

### ISSUE THREAD

**Issue by quenz** [lzacharkow/tabby-cat-support#4]
When you open a new tab, the address bar should automatically be selected, so you can instantly enter text into it without having to manually select it first. This is the behavior of a regular new tab, but Tabby Cat tabs don't do this.

**Comment by lzacharkow** [comment]
This was a bug with all newTab add-ons in Firefox and was resolved in v56. See the issue tracking of this bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1372996

I just updated my Firefox browser and can confirm that now when you open a new tab, the URL bar is selected so that you can begin typing without needing to clear first.

Hopefully in the future they make this even simpler by clearing the URL totally, but I think that the nature of Mozilla's focus on transparency means they like exposing where your new tab is coming from. At least that's what I've gathered from reading the issue threads 🤷🏽‍♀️

**Comment by lzacharkow** [comment]
So I just tested this a little further and found that if you open a new tab while your current URL bar is in focus not _not selected_ then the original behavior you described exists. 

But the new fix works if your current URL bar is in focus and selected, or if you're just browsing a website normally and decide to open a new tab without clicking the current URL bar. This covers the majority of cases. Unfortunately that edge case I found is a bug I don't have control over and rests with Firefox developers :(

**Comment by quenz** [comment]
I've been trying to reliably reproduce the bug for about an hour now, and I'm failing miserably. I'm hoping maybe I can report it on Firefox's bug tracker.

Could you help me out and give steps on exactly how to reliably reproduce the bug? I've tried so many different combinations, but every time I produce the bug, then try to do the same steps a second time, it doesn't work.

**Comment by lzacharkow** [comment]
Yeah it's a tough one to pin down! Here's how I can reproduce:

1. While on a page that is _not_ the newtab page, select the URL bar. (The URL can be highlighted or the cursor can be in the text. Both produce the bug.)
2. Open a new tab.
3. See bug—URL bar is not selected and the cursor is at the end of the newtab url.

Thanks for taking the initiative to report this! I really appreciate it. This bug makes it really annoying to use Tabby Cat or any new tab override.

Feel free to ping me on whatever issue you create if it's possible.

**Comment by quenz** [comment]
Unfortunately this doesn't seem to reliably reproduce the bug. I even created a new Firefox profile (essentially blank installation) to test with, and it still didn't seem to work. I can't seem to identify any consistent way to reproduce the behavior. 😩

In fact, right now the case seems to be that my address bar is not selected at all, and I open a new tab, and the address bar is still not selected. However, I just tried opening a new window, going to a random page, then opening a new tab, and the address bar is selected. 😕
