### ISSUE TITLE
[bug] In Firefox, tab in new window is default tab, not Tabby Cat tab

### ISSUE THREAD

**Issue by quenz** [lzacharkow/tabby-cat-support#5]
When you open a new window in Firefox, the tab in it is a default Firefox tab, rather than a Tabby Cat tab.

**Comment by lzacharkow** [comment]
I agree that this should be the default behavior, but Firefox regards the new window screen as different from the new tab screen. No worries, though! You can change this in your preferences...

#### How to make Tabby Cat your home page

1. Go to your **Preferences** by clicking Firefox > Preferences or by entering `about:preferences` in the URL bar.
2. Find the **Startup** preferences, and select the following options:
    - In **When Firefox starts** select "Show your home page"
    - In **Home page**, enter `moz-extension://b6960614-761b-434a-bbce-7774cbfb7d6d/public/index.html`.
        - _If that doesn't work, try opening a new tab and copying/pasting exactly what's in your URL bar when Tabby Cat opens._ 

Your preferences should look like this:
<img width="1079" alt="screen shot 2017-10-06 at 6 14 26 pm" src="https://user-images.githubusercontent.com/697973/31303470-093c1008-aac3-11e7-9914-c9e9984220a4.png">

Then open a new window and confirm that it's working. If not, let me know and I'll try and help!

**Comment by quenz** [comment]
This workaround does work, though the extension address seems to be different per user, or something, and it's a bit tricky to get hold of. If possible, you should make it so that this all works by default, though I understand if that might not be possible with how Firefox works currently.
