### ISSUE TITLE
[Bug] New tabs now contain a moz-extension URL

### ISSUE THREAD

**Issue by danielquinn** [lzacharkow/tabby-cat-support#7]
Whenever I open a new tab, the location bar is populated with something akin to:

    moz-extension://9f792912-3d07-48cc-959e-61cb72a776e5/public/index.html

The problem though is that it's a pretty common behaviour to open a new tab and start typing a search query or URL.  Now that this `moz-extension:` bit is there, I end up doing stuff like:

    moz-extension://9f792912-3d07-48cc-959e-61cb72a776e5/public/index.htmlpictures of kittens

and hitting enter -- which isn't ideal.

The best fix for this would be to have new tabs start with nothing in the location bar (the default) or at the very least start it with the text highlighted, so typing anything will automatically clear the text.  However, I'm not sure if highlighting the `moz-extension:` URL would inadvertently write to the Linux clipboard, so the first option would be preferable.

Platform: Firefox 56 on Ubuntu Linux with the following plugins:

* Bitwarden
* Containers on the go
* Cookie auto-delete
* Emoji Cheatsheet
* GNOME Shell integration
* HTTPS Everywhere
* Multi-account containers
* Privacy Badger
* Reddit Enhancement Suite
* Safe browsing (temporary) extension
* Test pilot

**Comment by lzacharkow** [comment]
Hey there, I agree but unfortunately this is what Firefox does by default :( See issue #4 for more detail.

**Comment by lzacharkow** [comment]
Closing because this is a bug with any New Tab add-on for Firefox and can only be fixed by the Mozilla team.
