### ISSUE TITLE
[Bug] The rocket-kitten is awkwardly scalped

### ISSUE THREAD

**Issue by Firesphere** [lzacharkow/tabby-cat-support#9]
![kitten](https://user-images.githubusercontent.com/680570/33225596-5e9091da-d1df-11e7-88ad-c04cf1378eb3.gif)
- Firefox Developer Edition 58.0b5 (64-bit)
- Windows 10

p.s.
Besides the cropping, this is the cutest kitten combo _ever_ !

p.p.s
It's not stored correctly on tabbycats 😞 http://tabbycats.club/cat/8o8170

**Comment by chef-meow** [comment]
it works perfectly fine for me perhaps try another browser

**Comment by stefnotch** [comment]
Seems to be fixed
